#strings
name = "joshua yamoah yankson"
print(len(name))
print(name.find("Y"))
print(name.capitalize())
print(name.upper())
print(name.lower())
print(name.isdigit())
print(name.isalpha())
print(name.count("y"))
print(name.replace("o" , "a"))
print(name * 2)
print(name.islower())
print(name.isupper())
print(name.isnumeric())
print(name.isprintable())
print(name.isspace())
print(name.startswith("y", 6))
print(name.endswith("joe"))
